# Generated by Django 5.0 on 2023-12-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdb',
            name='mobile',
        ),
        migrations.AddField(
            model_name='contactdb',
            name='sub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
